const AUDIT_ACTIONS = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',

  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',

  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',

  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  COUPON_DELETED: 'COUPON_DELETED',

  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  THEME_UPDATED: 'THEME_UPDATED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  MEMBER_INVITED: 'MEMBER_INVITED',
  MEMBER_REMOVED: 'MEMBER_REMOVED'
};

module.exports = {
  AUDIT_ACTIONS
};
