const INVENTORY_TRANSACTION_TYPES = {
  PURCHASE: 'PURCHASE',
  RESTOCK: 'RESTOCK',
  ADJUSTMENT: 'ADJUSTMENT',
  RETURN: 'RETURN',
  CANCELLATION: 'CANCELLATION',
  RESERVATION: 'RESERVATION',
  RELEASE: 'RELEASE'
};

module.exports = {
  INVENTORY_TRANSACTION_TYPES
};
