// Platform and Store Roles
const ROLES = {
  PLATFORM_OWNER: 'platform_owner',
  PLATFORM_ADMIN: 'platform_admin',
  STORE_OWNER: 'store_owner',
  STORE_ADMIN: 'store_admin',
  STORE_MANAGER: 'store_manager',
  STORE_STAFF: 'store_staff',
  CUSTOMER: 'customer'
};

// Granular System Permissions
const PERMISSIONS = {
  PRODUCTS_READ: 'products.read',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',

  ORDERS_READ: 'orders.read',
  ORDERS_UPDATE: 'orders.update',

  CUSTOMERS_READ: 'customers.read',

  INVENTORY_READ: 'inventory.read',
  INVENTORY_UPDATE: 'inventory.update',

  ANALYTICS_READ: 'analytics.read',

  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',

  THEMES_READ: 'themes.read',
  THEMES_UPDATE: 'themes.update',

  COUPONS_READ: 'coupons.read',
  COUPONS_CREATE: 'coupons.create',
  COUPONS_UPDATE: 'coupons.update',
  COUPONS_DELETE: 'coupons.delete',

  PLATFORM_MANAGE_TENANTS: 'platform.tenants.manage',
  PLATFORM_MANAGE_USERS: 'platform.users.manage',
  PLATFORM_MANAGE_PLANS: 'platform.plans.manage'
};

// Default Permission Mappings for Store & Platform Roles
const ROLE_PERMISSIONS = {
  [ROLES.PLATFORM_OWNER]: Object.values(PERMISSIONS),
  [ROLES.PLATFORM_ADMIN]: [
    PERMISSIONS.PLATFORM_MANAGE_TENANTS,
    PERMISSIONS.PLATFORM_MANAGE_USERS,
    PERMISSIONS.PLATFORM_MANAGE_PLANS,
    PERMISSIONS.ANALYTICS_READ
  ],
  [ROLES.STORE_OWNER]: [
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_UPDATE, PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.ORDERS_READ, PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.THEMES_READ, PERMISSIONS.THEMES_UPDATE,
    PERMISSIONS.COUPONS_READ, PERMISSIONS.COUPONS_CREATE, PERMISSIONS.COUPONS_UPDATE, PERMISSIONS.COUPONS_DELETE
  ],
  [ROLES.STORE_ADMIN]: [
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_UPDATE, PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.ORDERS_READ, PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.THEMES_READ, PERMISSIONS.THEMES_UPDATE,
    PERMISSIONS.COUPONS_READ, PERMISSIONS.COUPONS_CREATE, PERMISSIONS.COUPONS_UPDATE
  ],
  [ROLES.STORE_MANAGER]: [
    PERMISSIONS.PRODUCTS_READ, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.ORDERS_READ, PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.COUPONS_READ,
    PERMISSIONS.ANALYTICS_READ
  ],
  [ROLES.STORE_STAFF]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.INVENTORY_READ
  ],
  [ROLES.CUSTOMER]: []
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};
